E0229 15:26:10.720938437    4962 hpack_parser.cc:993]                  Error parsing 'content-type' metadata: invalid value
Unclassified exception: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNKNOWN
	details = "Stream removed"
	debug_error_string = "UNKNOWN:Error received from peer  {grpc_message:"Stream removed", grpc_status:2, created_time:"2024-02-29T15:26:10.721227149-08:00"}"
>
Traceback (most recent call last):
  File "/home/furry/Desktop/Files/Code/SPOT/SPOTy-Guard/app.py", line 60, in <module>
    robot_command_client = robot.ensure_client(RobotCommandClient.default_service_name)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/furry/Desktop/Files/Code/SPOT/spot/lib/python3.11/site-packages/bosdyn/client/robot.py", line 236, in ensure_client
    channel = self.ensure_channel(service_name, options=options)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/furry/Desktop/Files/Code/SPOT/spot/lib/python3.11/site-packages/bosdyn/client/robot.py", line 279, in ensure_channel
    self.sync_with_directory()
  File "/home/furry/Desktop/Files/Code/SPOT/spot/lib/python3.11/site-packages/bosdyn/client/robot.py", line 436, in sync_with_directory
    remote_services = self.list_services()
                      ^^^^^^^^^^^^^^^^^^^^
  File "/home/furry/Desktop/Files/Code/SPOT/spot/lib/python3.11/site-packages/bosdyn/client/robot.py", line 428, in list_services
    return dir_client.list()
           ^^^^^^^^^^^^^^^^^
  File "/home/furry/Desktop/Files/Code/SPOT/spot/lib/python3.11/site-packages/bosdyn/client/directory.py", line 58, in list
    return self.call(self._stub.ListServiceEntries, req, value_from_response=_list_value,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/furry/Desktop/Files/Code/SPOT/spot/lib/python3.11/site-packages/bosdyn/client/common.py", line 237, in processor
    return func(self, rpc_method, request, value_from_response=value_from_response,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/furry/Desktop/Files/Code/SPOT/spot/lib/python3.11/site-packages/bosdyn/client/common.py", line 350, in call
    six.raise_from(translate_exception(e), None)
  File "<string>", line 3, in raise_from
bosdyn.client.exceptions.RpcError: RpcError: An error occurred trying to reach a service on the robot.
